/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.h
 #	source generated by 4D Plugin Wizard
 #	Project : window-switching
 #	author : miyako
 #	2015/07/10
 #
 # --------------------------------------------------------------------------------*/

#if VERSIONWIN
#include "Shlwapi.h"
HWND MDI_getHWND(void);
#endif

// --- Window Switching
void ENABLE_WINDOW_SWITCHING(sLONG_PTR *pResult, PackagePtr pParams);
void DISABLE_WINDOW_SWITCHING(sLONG_PTR *pResult, PackagePtr pParams);
